#BLUEMIX
mqtt:
  image:          registry.eu-gb.bluemix.net/airq_containers/mqtt:dev
  # container_name: mqtt
  mem_limit:      128
  expose:
    - "1883"
  log_driver:     "none"
storage-server:
  image:          registry.eu-gb.bluemix.net/airq_containers/storage-server:latest
  container_name: storage-server
  mem_limit:      128
  ports:
    - "3000:3000"
station:
  image:          registry.eu-gb.bluemix.net/airq_containers/station:latest
  container_name: station
  mem_limit:      64
  links:
    # - mqtt
    - haproxy
    - data-transformer
    - diagnostic
data-transformer:
  image:          registry.eu-gb.bluemix.net/airq_containers/data-transformer:latest
  container_name: data-transformer
  mem_limit:      64
  links:
    # - mqtt
    - haproxy
    - storage-server
  env_file:
    - prod-variables.env
diagnostic:
  image:          registry.eu-gb.bluemix.net/airq_containers/diagnostic:latest
  container_name: diagnostic
  mem_limit:      64
  links:
    # - mqtt
    - haproxy
    - storage-server
  env_file:
    - prod-variables.env
forecast:
  image:          registry.eu-gb.bluemix.net/airq_containers/forecast:latest
  container_name: forecast
  mem_limit:      64
  links:
    # - mqtt
    - haproxy
    - storage-server
haproxy:
  image :    registry.eu-gb.bluemix.net/airq_containers/haproxy:latest
  container_name: haproxy
  mem_limit: 128
  links:
    - mqtt
  ports:
    - "request:1883:1883"
