version: '3'
services:
  aqi:
    #context: ./docker-aqi
    build: ./docker-aqi
    container_name: docker-aqi
    # volumes:
    #  - .:/app
  data-transformer:
    build: ./docker-data-transformer
    container_name: data-transformer
    # volumes:
    #  - .:/app
  mqtt:
    image: "toke/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
