#aqi:
 # build:          ./aqi
 # image:        registry.eu-gb.bluemix.net/airq_containers/aqi:latest #aqi
 # container_name: aqi
 # mem_limit:      64m
 # links:
 #  - mqtt
station:
  build:          ./station
  # image:        registry.eu-gb.bluemix.net/airq_containers/aqi:latest #aqi
  container_name: station
  mem_limit:      64m
  links:
    - mqtt
    - storage-server
data-transformer:
  build:          ./data-transformer
  # image:        registry.eu-gb.bluemix.net/airq_containers/data-transformer:latest #aqi
  container_name: data-transformer
  mem_limit:      64m
  links:
    - mqtt
    - aqi
diagnostic:
  build:          ./diagnostic
  # image:        #TODO
  container_name: diagnostic
  mem_limit:      64m
  links:
    - mqtt
    - aqi
    - data-transformer
mqtt:
  image:          "toke/mosquitto"
  # image:        registry.eu-gb.bluemix.net/airq_containers/mqtt:dev # mqtt
  container_name: mqtt
  mem_limit:      128m
  # ports:
    # - "134.168.40.167:1883:1883"
    # - "9001:9001"
  expose:
    - "1883"
    - "9001"
storage-server:
  build: ./storage-server
  # image: registry.eu-gb.bluemix.net/airq_containers/storage-server:latest
  container_name: storage-server
  mem_limit: 128m
  expose:
    - "3000"