# IMPORTANT: comment 'local' lines and uncomment 'bluemix' lines to deploy
station:
  # build:        ./station # local
  image:          registry.eu-gb.bluemix.net/airq_containers/station:latest # bluemix
  container_name: station
  # mem_limit:      64m # local
  mem_limit:      64 # bluemix
  links:
    - mqtt
data-transformer:
  # build:          ./data-transformer # local
  image:        registry.eu-gb.bluemix.net/airq_containers/data-transformer:latest # bluemix
  container_name: data-transformer
  # mem_limit:      64m # local
  mem_limit:      64 # bluemix
  links:
    - mqtt
    - storage-server
diagnostic:
  # build:          ./diagnostic # local
  image:        registry.eu-gb.bluemix.net/airq_containers/diagnostic:latest # bluemix
  container_name: diagnostic
  # mem_limit:      64m # local
  mem_limit:      64 # bluemix
  links:
    - mqtt
    - storage-server
mqtt:
  # image:          "toke/mosquitto" # local
  image:        registry.eu-gb.bluemix.net/airq_containers/mqtt:dev # bluemix
  container_name: mqtt
  # mem_limit:      128m # local
  mem_limit:      128 # bluemix
  ports:        # bluemix
    - "134.168.40.167:1883:1883" # bluemix
  # expose:         # local
    # - "1883" # local
storage-server:
  # build:          ./storage-server # local
  image:        registry.eu-gb.bluemix.net/airq_containers/storage-server:latest # bluemix
  container_name: storage-server
  # mem_limit:      128m # local
  mem_limit:      128 # bluemix
  ports:        # bluemix
    - "134.168.44.231:3000:3000" # bluemix
  # expose:         # local
    # - "3000" # local
