version: '3'
services:
  aqi:
    build: ./aqi
    container_name: aqi
    volumes:
      - ./aqi/src:/app
    depends_on:
      - mqtt
  data-transformer:
    build: ./data-transformer
    container_name: data-transformer
    volumes:
      - ./data-transformer/src:/app
    depends_on:
      - mqtt
  mqtt:
    image: "toke/mosquitto"
    container_name: mqtt
    # ports:
    #   - "1883:1883"
    #   - "9001:9001"
