# LOCAL
mqtt:
  image:          "toke/mosquitto"
  # container_name: mqtt
  mem_limit:      128m
  expose:
    - "1883"
  log_driver:     "none"
storage-server:
  build:          ./storage-server
  container_name: storage-server
  mem_limit:      128m
  expose:
    - "3000"
station:
  build:          ./station
  container_name: station
  mem_limit:      64m
  links:
    # - mqtt
    - haproxy
    - data-transformer
    - diagnostic
data-transformer:
  build:          ./data-transformer
  container_name: data-transformer
  mem_limit:      64m
  links:
    # - mqtt
    - haproxy
    - storage-server
  env_file:
    - dev-variables.env
diagnostic:
  build:          ./diagnostic
  container_name: diagnostic
  mem_limit:      64m
  links:
    # - mqtt
    - haproxy
    - storage-server
  env_file:
    - dev-variables.env
forecast:
  build:          ./forecast
  container_name: forecast
  mem_limit:      64m
  links:
    # - mqtt
    - haproxy
    - storage-server
haproxy:
  build :    ./haproxy
  container_name: haproxy
  mem_limit: 128m
  links:
    - mqtt
  expose:
    - "1883"
web-server:
  build:          ./web-server
  container_name: web-server
  mem_limit:      128m
  expose:
    - "8080"
